# Generated by Django 6.0.2 on 2026-04-17 14:05

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('signature_type', models.CharField(blank=True, max_length=20, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('made_at', models.CharField(blank=True, max_length=255, null=True)),
                ('advance_payment_months', models.IntegerField(default=1)),
                ('rent_due_day', models.IntegerField(default=5)),
                ('witness_1', models.CharField(blank=True, max_length=150, null=True)),
                ('witness_2', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promptpay_no', models.CharField(blank=True, max_length=20, null=True)),
                ('promptpay_name', models.CharField(blank=True, max_length=100, null=True)),
                ('system_version', models.CharField(default='1.0.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_info',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('id_card_no', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_line', models.BooleanField(default=False)),
                ('sync_calendar', models.BooleanField(default=False)),
                ('calendar_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.contract')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'โอนเงินบัญชีธนาคาร'), ('cash', 'เงินสด')], default='bank_transfer', max_length=20)),
                ('slip_image_url', models.FileField(blank=True, db_column='slip_image_url', max_length=255, null=True, upload_to=services.models.get_slip_path)),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('verified', 'ยืนยันแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.invoice')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.roomtype'),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.room')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.tenant')),
            ],
            options={
                'db_table': 'maintenance_requests',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tenant'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'รถยนต์'), ('motorcycle', 'รถจักรยานยนต์'), ('other', 'อื่นๆ')], default='car', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='services.tenant')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
